{"componentChunkName":"component---node-modules-gatsby-theme-replica-src-templates-tag-tsx","path":"/tech/tag/promise链","result":{"data":{"allMdx":{"nodes":[{"id":"e26cc823-9ea7-5f02-868c-7841adba0c9c","excerpt":"对 promise 这个概念之前已经有了一些浅显的理解， 相关文章->戳这里 ，最近又有了一些新的理解。 .then()的时候到底是在 then 什么… 首先要理解…Promise 是一个对象，有 then()方法的对象 then()的入参是一个函数，通常在 promise 链中，入参是 一个返回 promise 的函数 ，这句话好像有点拗口，就是说入参是一个函数，这个函数会 return…","frontmatter":{"title":"对Promise中的resolve，reject，catch的理解","date":"2015-12-22T03:36:07.000Z","tags":["promise chain","promise链"]},"fields":{"slug":"/post/20151222-understand-resolve-reject-catch-of-promise/"},"slug":"20151222-understand-resolve-reject-catch-of-promise"}]}},"pageContext":{"tag":"promise链"}},"staticQueryHashes":["2873555300"]}